name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  blurry_modal_progress_hud: ^1.1.1
  cloud_firestore: ^4.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
